version: '3'
services:
  app:
    build: .
    image: demoapi
    container_name: dotnetapp
    ports:
      - 5000:80
    deploy:
      resources:
        limits:
          cpus: 80m
          memory: 50M
        reservations:
          cpus: 30m
          memory: 10M
